language: node_js
before_install:
  - "export CODECLIMATE_REPO_TOKEN=04344935d439718d5982fddb88c6e39a9ca9fc057f8eea3399a05f139dac6a36"
install:
  - "npm install npm -g"
  - "npm install grunt-cli -g"
  - "npm install codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt travis"
  - "if [[ $(node -v) == v0.10* ]]; then codeclimate < coverage/coverage.lcov; fi"
node_js:
  - "0.8"
  - "0.10"
