language: node_js
sudo: false
addons:
  code_climate:
    repo_token: '04344935d439718d5982fddb88c6e39a9ca9fc057f8eea3399a05f139dac6a36'
install:
  - "npm install npm -g"
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - 'node_modules'
